---
- hosts: webserver
  remote_user: root
  roles:
    - common
    - { role: kamaln7.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10 }
    - nickhammond.logrotate
    - joshualund.ruby-2_1
    - ANXS.postgresql
    - webserver
