# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "webserver" do |web|
    web.vm.hostname = "webserver"
    web.vm.network "private_network", ip: "33.33.33.22"
    web.vm.provider "virtualbox" do |provider|
      provider.name = "Dan Web-Staging"
      provider.customize ["modifyvm", :id, "--memory", "512"]
    end

    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "web-playbook.yml"
      ansible.inventory_path = "inventory-stage.ini"
      ansible.host_key_checking = false
      ansible.sudo = true
    end
  end
end
