default: &default
  adapter: postgresql
  encoding: utf8
  database: skedge
  pool: 5
  username:
  password:

development:
  <<: *default

test:
  <<: *default
  database: skedge_test

staging:
  <<: *default
  database: skedge_staging

production:
  <<: *default
